version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: resume-analyzer-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Orkun123.
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  web:
    image: resume-analyzer-web
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-analyzer-web
    ports:
      - "8080:8080"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DATABASE_CONNECTION_STRING=Server=db,1433;Database=ResumeAnalyzerDb;User Id=sa;Password=Orkun123.;TrustServerCertificate=True;
      - OLLAMA_BASEURL=http://host.docker.internal:11434
      - OLLAMA_MODELNAME=${OLLAMA_MODELNAME}
      - GOOGLE_DRIVE_CLIENT_ID=${GOOGLE_DRIVE_CLIENT_ID}
      - GOOGLE_DRIVE_CLIENT_SECRET=${GOOGLE_DRIVE_CLIENT_SECRET}
      - GOOGLE_DRIVE_REFRESH_TOKEN=${GOOGLE_DRIVE_REFRESHTOKEN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}

volumes:
  mssql_data:
